import { Event } from '../types';

export const mockEvents: Event[] = [
  {
    id: '1',
    speaker: 'Dr. Sarah Johnson',
    speakerBio: 'Leading expert in AI and Machine Learning with over 15 years of experience.',
    speakerImage: 'https://i.pravatar.cc/150?img=1',
    title: 'The Future of Artificial Intelligence',
    description:
      'Explore the latest advancements in AI and how they will shape our future. This comprehensive talk covers machine learning, neural networks, and ethical considerations in AI development.',
    date: 'Friday',
    time: '09:00 - 10:30',
    location: 'Main Hall A',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400',
    category: 'Technology',
    tags: ['AI', 'Machine Learning', 'Innovation'],
    latitude: 37.7749,
    longitude: -122.4194,
    isFavorite: false,
  },
  {
    id: '2',
    speaker: 'Mark Thompson',
    speakerBio: 'Renowned UX designer and author of "Design for Everyone".',
    speakerImage: 'https://i.pravatar.cc/150?img=2',
    title: 'Design Thinking Workshop',
    description:
      'A hands-on workshop exploring design thinking methodologies and how to apply them to real-world problems. Learn practical techniques for innovation.',
    date: 'Friday',
    time: '11:00 - 12:30',
    location: 'Workshop Room 1',
    image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400',
    category: 'Design',
    tags: ['UX', 'Design', 'Workshop'],
    latitude: 37.7750,
    longitude: -122.4195,
    isFavorite: false,
  },
  {
    id: '3',
    speaker: 'Emily Chen',
    speakerBio: 'Startup founder and venture capitalist with 3 successful exits.',
    speakerImage: 'https://i.pravatar.cc/150?img=3',
    title: 'Building Scalable Startups',
    description:
      'Learn from successful entrepreneurs about building and scaling startups. Covering funding, team building, product development, and growth strategies.',
    date: 'Saturday',
    time: '09:00 - 10:30',
    location: 'Main Hall B',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400',
    category: 'Business',
    tags: ['Startups', 'Entrepreneurship', 'Growth'],
    latitude: 37.7748,
    longitude: -122.4196,
    isFavorite: false,
  },
  {
    id: '4',
    speaker: 'Prof. James Miller',
    speakerBio: 'Professor of Computer Science at MIT, specializing in cybersecurity.',
    speakerImage: 'https://i.pravatar.cc/150?img=4',
    title: 'Cybersecurity in Modern Applications',
    description:
      'Understanding the latest security threats and how to protect your applications. Best practices for secure coding and system architecture.',
    date: 'Saturday',
    time: '11:00 - 12:30',
    location: 'Tech Room A',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400',
    category: 'Technology',
    tags: ['Security', 'Development', 'Best Practices'],
    latitude: 37.7751,
    longitude: -122.4193,
    isFavorite: false,
  },
  {
    id: '5',
    speaker: 'Lisa Rodriguez',
    speakerBio: 'DevOps engineer and cloud architecture specialist.',
    speakerImage: 'https://i.pravatar.cc/150?img=5',
    title: 'Cloud Architecture Best Practices',
    description:
      'Deep dive into cloud architecture patterns, microservices, and containerization. Learn how to build resilient, scalable cloud applications.',
    date: 'Saturday',
    time: '14:00 - 15:30',
    location: 'Tech Room B',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    category: 'Technology',
    tags: ['Cloud', 'DevOps', 'Architecture'],
    latitude: 37.7752,
    longitude: -122.4197,
    isFavorite: false,
  },
  {
    id: '6',
    speaker: 'David Park',
    speakerBio: 'Mobile development expert with apps used by millions.',
    speakerImage: 'https://i.pravatar.cc/150?img=6',
    title: 'Mobile Development Trends 2024',
    description:
      'Explore the latest trends in mobile development including React Native, Flutter, and native development. Performance optimization and user experience.',
    date: 'Sunday',
    time: '09:00 - 10:30',
    location: 'Main Hall A',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
    category: 'Technology',
    tags: ['Mobile', 'React Native', 'Development'],
    latitude: 37.7749,
    longitude: -122.4198,
    isFavorite: false,
  },
  {
    id: '7',
    speaker: 'Rachel Green',
    speakerBio: 'Leadership coach and organizational psychologist.',
    speakerImage: 'https://i.pravatar.cc/150?img=7',
    title: 'Leadership in Tech',
    description:
      'Developing leadership skills for the tech industry. How to build and lead effective teams, foster innovation, and create positive work culture.',
    date: 'Sunday',
    time: '11:00 - 12:30',
    location: 'Workshop Room 2',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    category: 'Leadership',
    tags: ['Leadership', 'Management', 'Culture'],
    latitude: 37.7747,
    longitude: -122.4192,
    isFavorite: false,
  },
  {
    id: '8',
    speaker: 'Alex Kumar',
    speakerBio: 'Data scientist and AI researcher at Google.',
    speakerImage: 'https://i.pravatar.cc/150?img=8',
    title: 'Data Science & Analytics',
    description:
      'Learn how to extract insights from data using modern tools and techniques. From data collection to visualization and machine learning.',
    date: 'Sunday',
    time: '14:00 - 15:30',
    location: 'Tech Room A',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    category: 'Data Science',
    tags: ['Data', 'Analytics', 'ML'],
    latitude: 37.7753,
    longitude: -122.4191,
    isFavorite: false,
  },
];
